name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - cuda-version: "none"
            image-tags: "cpu,latest"
          - cuda-version: "3.0"
            tags: "gpu-cuda-3.0"
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          build_args: CUDA_VERSION=${{ matrix.cuda-version }}
          push: false
